#!/bin/sh
# shellcheck disable=SC2155
unsetopt PROMPT_SP 2>/dev/null
# export EDITOR="nvim"
# export TERMINAL="kitty"
# export TERMINAL_PROG="kitty"
# export TERMINAL="chromium"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
PATH="$PATH:/home/alex/.cargo/bin"
